### ISSUE TITLE
Erreurs dans la console

### ISSUE THREAD

**Issue by devmlb** [Maxence-r/UNsalib_Modern-Timetable-Viewer#4]
Des fichiers images demandés n'existent pas sur le serveur

![image](https://github.com/user-attachments/assets/93a46aeb-2be1-4298-a1b0-d63b92ef1255)

**Comment by Maxence-r** [comment]
Ethan doit retirer tout les badges "info" et retirer toutes les salles où certains badges sont des strings vides, j'ai par ailleurs remarqué que certaines salles manquaient des badges. @EthannAllain
